### ISSUE TITLE
Recipes

### ISSUE THREAD

**Issue by rbnswartz** [PilzAdam/carts#4]
Are we going to get a crafting recipe for the power and brake rails any time soon?

**Comment by Uberi** [comment]
I suggest the following:

```
Steel MeseCrystal Steel
Steel Stick Steel
Steel MeseCrystal Steel
```

As well as:

```
Steel Stick Steel
Steel MeseCrystal Steel
Steel Stick Steel
```

Both do not require mesecons, but imply that mesecons will work with them too. Plus, the cost is about right for something of this nature.

**Comment by PilzAdam** [comment]
087c814e11c55d4879d727b84f896fe70de20f2f
